/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
	'use strict';
	function supportsProperty(p) {
		var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
			i,
			div = document.createElement('div'),
			ret = p in div.style;
		if (!ret) {
			p = p.charAt(0).toUpperCase() + p.substr(1);
			for (i = 0; i < prefixes.length; i += 1) {
				ret = prefixes[i] + p in div.style;
				if (ret) {
					break;
				}
			}
		}
		return ret;
	}
	var icons;
	if (!supportsProperty('fontFeatureSettings')) {
		icons = {
			'actionboard': '&#xe631;',
			'addressbook': '&#xe632;',
			'addwindow': '&#xe633;',
			'alarmclock': '&#xe634;',
			'alt': '&#xe635;',
			'apple': '&#xe636;',
			'appletwo': '&#xe637;',
			'leftthree': '&#xe638;',
			'rightthree': '&#xe639;',
			'left': '&#xe63a;',
			'right': '&#xe63b;',
			'lefthree': '&#xe63c;',
			'righthree': '&#xe63d;',
			'downtwo': '&#xe63e;',
			'down': '&#xe63f;',
			'lefttwo': '&#xe640;',
			'leftfour': '&#xe641;',
			'righttwo': '&#xe642;',
			'rightfour': '&#xe643;',
			'uptwo': '&#xe644;',
			'up': '&#xe645;',
			'asterisk': '&#xe646;',
			'backtwo': '&#xe647;',
			'back': '&#xe648;',
			'batterythree': '&#xe649;',
			'batterytwo': '&#xe64a;',
			'batterycharge': '&#xe64b;',
			'battery': '&#xe64c;',
			'bell': '&#xe64d;',
			'blankdocument': '&#xe64e;',
			'bluetooth': '&#xe64f;',
			'book': '&#xe650;',
			'bookmark': '&#xe651;',
			'bottle': '&#xe652;',
			'bowlchopsticks': '&#xe653;',
			'bowlspoon': '&#xe654;',
			'bowl': '&#xe655;',
			'box': '&#xe656;',
			'briefcase': '&#xe657;',
			'bright': '&#xe658;',
			'burn': '&#xe659;',
			'bus': '&#xe65a;',
			'cabinet': '&#xe65b;',
			'calculator': '&#xe65c;',
			'calendartwo': '&#xe65d;',
			'calendar': '&#xe65e;',
			'camera': '&#xe65f;',
			'cassette': '&#xe660;',
			'cautiontwo': '&#xe661;',
			'caution': '&#xe662;',
			'cd': '&#xe663;',
			'cellphone': '&#xe664;',
			'checktwo': '&#xe665;',
			'checkwindow': '&#xe666;',
			'check': '&#xe667;',
			'chefhat': '&#xe668;',
			'chattwo': '&#xe669;',
			'chatthree': '&#xe66a;',
			'chat': '&#xe66b;',
			'clipboardtwo': '&#xe66c;',
			'clipboardcheck': '&#xe66d;',
			'clipboarddelete': '&#xe66e;',
			'clipboard': '&#xe66f;',
			'clock': '&#xe670;',
			'closewindow': '&#xe671;',
			'cloudcheck': '&#xe672;',
			'clouddelete': '&#xe673;',
			'clouddownload': '&#xe674;',
			'clouduploadtwo': '&#xe675;',
			'cloudupload': '&#xe676;',
			'cloud': '&#xe677;',
			'clubs': '&#xe678;',
			'dashboard': '&#xe679;',
			'deletetwo': '&#xe67a;',
			'deletedocument': '&#xe67b;',
			'delete': '&#xe67c;',
			'diagonalnavigation': '&#xe67d;',
			'diamonds': '&#xe67e;',
			'dice': '&#xe67f;',
			'dim': '&#xe680;',
			'document': '&#xe681;',
			'downloadtwo': '&#xe682;',
			'download': '&#xe683;',
			'drumsticktwo': '&#xe684;',
			'drumstick': '&#xe685;',
			'earth': '&#xe686;',
			'edit': '&#xe687;',
			'egg': '&#xe688;',
			'eject': '&#xe689;',
			'mailopened': '&#xe68a;',
			'outbox': '&#xe68b;',
			'exitfullscreentwo': '&#xe68c;',
			'exitfullscreen': '&#xe68d;',
			'expand': '&#xe68e;',
			'fastforward': '&#xe68f;',
			'female': '&#xe690;',
			'filmstrip': '&#xe691;',
			'firewire': '&#xe692;',
			'firstaid': '&#xe693;',
			'flagtwo': '&#xe694;',
			'flag': '&#xe695;',
			'flashdrive': '&#xe696;',
			'flashlight': '&#xe697;',
			'flasktwo': '&#xe698;',
			'flask': '&#xe699;',
			'floppydisk': '&#xe69a;',
			'folderadd': '&#xe69b;',
			'forwardtwo': '&#xe69c;',
			'forward': '&#xe69d;',
			'fridge': '&#xe69e;',
			'fullscreen': '&#xe69f;',
			'gas': '&#xe6a0;',
			'gauge': '&#xe6a1;',
			'gavel': '&#xe6a2;',
			'gear': '&#xe6a3;',
			'glass': '&#xe6a4;',
			'globe': '&#xe6a5;',
			'graphtwo': '&#xe6a6;',
			'graphthree': '&#xe6a7;',
			'graph': '&#xe6a8;',
			'grilltwo': '&#xe6a9;',
			'grill': '&#xe6aa;',
			'headphones': '&#xe6ab;',
			'heart': '&#xe6ac;',
			'hearts': '&#xe6ad;',
			'home': '&#xe6ae;',
			'indent': '&#xe6af;',
			'infotwo': '&#xe6b0;',
			'info': '&#xe6b1;',
			'ipad': '&#xe6b2;',
			'iphone': '&#xe6b3;',
			'ipod': '&#xe6b4;',
			'jar': '&#xe6b5;',
			'ketchup': '&#xe6b6;',
			'key': '&#xe6b7;',
			'keyboard': '&#xe6b8;',
			'king': '&#xe6b9;',
			'knifefork': '&#xe6ba;',
			'lamp': '&#xe6bb;',
			'layouttwo': '&#xe6bc;',
			'layoutthree': '&#xe6bd;',
			'layout': '&#xe6be;',
			'leaf': '&#xe6bf;',
			'lifesaver': '&#xe6c0;',
			'lightbulb': '&#xe6c1;',
			'link': '&#xe6c2;',
			'list': '&#xe6c3;',
			'locktwo': '&#xe6c4;',
			'lock': '&#xe6c5;',
			'login': '&#xe6c6;',
			'logout': '&#xe6c7;',
			'magnet': '&#xe6c8;',
			'magnifyingglass': '&#xe6c9;',
			'male': '&#xe6ca;',
			'map': '&#xe6cb;',
			'medal': '&#xe6cc;',
			'megaphone': '&#xe6cd;',
			'mictwo': '&#xe6cf;',
			'mic': '&#xe6d0;',
			'minimize': '&#xe6df;',
			'move': '&#xe6e0;',
			'muffin': '&#xe6e1;',
			'multiplewindows': '&#xe6e2;',
			'musictwo': '&#xe6e3;',
			'stereo': '&#xe6e4;',
			'newdocument': '&#xe6e5;',
			'next': '&#xe6e6;',
			'no': '&#xe6e7;',
			'outdent': '&#xe6e8;',
			'outlet': '&#xe6e9;',
			'page': '&#xe6ea;',
			'paintbrush': '&#xe6eb;',
			'panelclose': '&#xe6ec;',
			'panelshow': '&#xe6ed;',
			'paperclip': '&#xe6ee;',
			'papertray': '&#xe6ef;',
			'pause': '&#xe6f0;',
			'pen': '&#xe6f1;',
			'pencil': '&#xe6f2;',
			'people': '&#xe6f3;',
			'person': '&#xe6f4;',
			'phone': '&#xe6f5;',
			'photo': '&#xe6f6;',
			'photostwo': '&#xe6f7;',
			'photosblank': '&#xe6f8;',
			'photos': '&#xe6f9;',
			'piechart': '&#xe6fa;',
			'pill': '&#xe6fb;',
			'pizzatwo': '&#xe6fc;',
			'pizza': '&#xe6fd;',
			'plane': '&#xe6fe;',
			'plate': '&#xe6ff;',
			'play': '&#xe700;',
			'plug': '&#xe701;',
			'plus': '&#xe702;',
			'popsicletwo': '&#xe703;',
			'popsicle': '&#xe704;',
			'power': '&#xe705;',
			'previous': '&#xe706;',
			'printertwo': '&#xe707;',
			'printer': '&#xe708;',
			'radioactive': '&#xe709;',
			'record': '&#xe70a;',
			'recycletwo': '&#xe70b;',
			'recycle': '&#xe70c;',
			'repeat': '&#xe70d;',
			'replay': '&#xe70e;',
			'returntwo': '&#xe70f;',
			'return': '&#xe710;',
			'rewind': '&#xe711;',
			'scope': '&#xe712;',
			'share': '&#xe713;',
			'shield': '&#xe714;',
			'shock': '&#xe715;',
			'shoppingbag': '&#xe716;',
			'shuffle': '&#xe717;',
			'soda': '&#xe718;',
			'spatula': '&#xe719;',
			'speaker': '&#xe71a;',
			'squarechattwo': '&#xe71b;',
			'squarechatthree': '&#xe71c;',
			'squarechat': '&#xe71d;',
			'startwo': '&#xe71e;',
			'star': '&#xe71f;',
			'statsdowntwo': '&#xe720;',
			'statsdown': '&#xe721;',
			'statsuptwo': '&#xe722;',
			'statsup': '&#xe723;',
			'stop': '&#xe724;',
			'subtractwindow': '&#xe725;',
			'tag': '&#xe726;',
			'tea': '&#xe727;',
			'testtube': '&#xe728;',
			'thumbtack': '&#xe729;',
			'thumbnaillist': '&#xe72a;',
			'thumbnailssmall': '&#xe72b;',
			'thumbnails': '&#xe72c;',
			'tie': '&#xe72d;',
			'traffic': '&#xe72e;',
			'train': '&#xe72f;',
			'trash': '&#xe730;',
			'trophy': '&#xe731;',
			'tv': '&#xe732;',
			'umbrella': '&#xe733;',
			'unlocktwo': '&#xe734;',
			'unlock': '&#xe735;',
			'uploadtwo': '&#xe736;',
			'upload': '&#xe737;',
			'usb': '&#xe738;',
			'useradd': '&#xe739;',
			'userdeletetwo': '&#xe73a;',
			'userdelete': '&#xe73b;',
			'vinyl': '&#xe73c;',
			'volumeadd': '&#xe73d;',
			'volumelevels': '&#xe73e;',
			'volumemax': '&#xe73f;',
			'volumeoff': '&#xe740;',
			'volumesubtract': '&#xe741;',
			'volume': '&#xe742;',
			'watch': '&#xe743;',
			'water': '&#xe744;',
			'weblayout': '&#xe745;',
			'wifi': '&#xe746;',
			'window': '&#xe747;',
			'windows': '&#xe748;',
			'winetwo': '&#xe749;',
			'wine': '&#xe74a;',
			'wrench': '&#xe74b;',
			'zip': '&#xe74c;',
			'zoomtwo': '&#xe74d;',
			'zoom': '&#xe74e;',
			'zoomouttwo': '&#xe74f;',
			'zoomout': '&#xe750;',
			'music': '&#xe600;',
			'memo': '&#xe6ce;',
			'cart': '&#xe602;',
			'checkthree': '&#xe603;',
			'code': '&#xe604;',
			'commandprompt': '&#xe605;',
			'command': '&#xe606;',
			'compass': '&#xe607;',
			'computermonitor': '&#xe608;',
			'mouse': '&#xe609;',
			'contrast': '&#xe60a;',
			'coverflow': '&#xe60b;',
			'creditcard': '&#xe60c;',
			'crown': '&#xe60d;',
			'cube': '&#xe60e;',
			'mail': '&#xe611;',
			'inbox': '&#xe612;',
			'read': '&#xe613;',
			'eye': '&#xe614;',
			'fish': '&#xe615;',
			'folderdelete': '&#xe616;',
			'folder': '&#xe617;',
			'controller': '&#xe619;',
			'glasses': '&#xe61a;',
			'hourglass': '&#xe61b;',
			'icecreamtwo': '&#xe61c;',
			'icecream': '&#xe61d;',
			'icecreamfour': '&#xe61e;',
			'icecreamthree': '&#xe61f;',
			'identification': '&#xe620;',
			'locationpin': '&#xe621;',
			'mask': '&#xe622;',
			'moustache': '&#xe623;',
			'mustard': '&#xe627;',
			'mutetwo': '&#xe628;',
			'mute': '&#xe629;',
			'servingtray': '&#xe630;',
			'spades': '&#xe6d1;',
			'sync': '&#xe6d3;',
			'applefour': '&#xe62a;',
			'applefive': '&#xe62b;',
			'applesix': '&#xe62c;',
			'applethree': '&#xe62d;',
			'behance': '&#xe62e;',
			'behancetwo': '&#xe62f;',
			'behancethree': '&#xe6d2;',
			'behancefour': '&#xe6d4;',
			'bloggertwo': '&#xe6d5;',
			'bloggerthree': '&#xe6d6;',
			'bloggerfour': '&#xe6d7;',
			'blogger': '&#xe6d8;',
			'dribbbletwo': '&#xe6d9;',
			'dribbblethree': '&#xe6da;',
			'dribbblefour': '&#xe6db;',
			'dribbble': '&#xe6dc;',
			'facebooktwo': '&#xe6dd;',
			'facebookthree': '&#xe6de;',
			'facebookfour': '&#xe751;',
			'facebook': '&#xe752;',
			'linkedintwo': '&#xe753;',
			'linkedinthree': '&#xe754;',
			'linkedinfour': '&#xe755;',
			'linkedin': '&#xe756;',
			'myspacetwo': '&#xe757;',
			'myspacethree': '&#xe758;',
			'myspacefour': '&#xe759;',
			'myspace': '&#xe75a;',
			'rsstwo': '&#xe75b;',
			'rssthree': '&#xe75c;',
			'rssfour': '&#xe75d;',
			'rss': '&#xe75e;',
			'skypetwo': '&#xe75f;',
			'skypethree': '&#xe760;',
			'skypefour': '&#xe761;',
			'skype': '&#xe762;',
			'stumbleupontwo': '&#xe763;',
			'stumbleuponthree': '&#xe764;',
			'stumbleuponfour': '&#xe765;',
			'stumbleupon': '&#xe766;',
			'twittertwo': '&#xe767;',
			'twitterthree': '&#xe768;',
			'twitterfour': '&#xe769;',
			'twitter': '&#xe76a;',
			'vimeotwo': '&#xe76b;',
			'vimeothree': '&#xe76c;',
			'vimeofour': '&#xe76d;',
			'vimeo': '&#xe76e;',
			'windowstwo': '&#xe76f;',
			'windowsthree': '&#xe770;',
			'windowsfour': '&#xe771;',
			'wordpresstwo': '&#xe773;',
			'wordpressthree': '&#xe774;',
			'wordpressfour': '&#xe775;',
			'wordpress': '&#xe776;',
			'yahootwo': '&#xe777;',
			'yahoothree': '&#xe778;',
			'yahoofour': '&#xe779;',
			'yahoo': '&#xe77a;',
			'youtubetwo': '&#xe77b;',
			'youtubethree': '&#xe77c;',
			'youtubefour': '&#xe77d;',
			'youtube': '&#xe77e;',
			'0': 0
		};
		delete icons['0'];
		window.icomoonLiga = function (els) {
			var classes,
				el,
				i,
				innerHTML,
				key;
			els = els || document.getElementsByTagName('*');
			if (!els.length) {
				els = [els];
			}
			for (i = 0; ; i += 1) {
				el = els[i];
				if (!el) {
					break;
				}
				classes = el.className;
				if (/icon-/.test(classes)) {
					innerHTML = el.innerHTML;
					if (innerHTML && innerHTML.length > 1) {
						for (key in icons) {
							if (icons.hasOwnProperty(key)) {
								innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
							}
						}
						el.innerHTML = innerHTML;
					}
				}
			}
		};
		window.icomoonLiga();
	}
}());